plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.3.cjs

packageExtensions:
  '@commitlint/cli@*':
    dependencies:
      ts-node: '*'
      typescript: '*'
      '@types/node': '*'
  '@digitalroute/cz-conventional-changelog-for-jira@*':
    dependencies:
      ts-node: '*'
      typescript: '*'
      '@types/node': '*'
  '@nrwl/devkit@*':
    dependencies:
      typescript: '*'
  '@nrwl/jest@*':
    dependencies:
      typescript: '*'
      nx: '14'
  '@nrwl/js@*':
    dependencies:
      nx: '14'
  '@nrwl/linter@*':
    dependencies:
      typescript: '*'
  '@ryansonshine/cz-conventional-changelog@*':
    dependencies:
      ts-node: '*'
      '@types/node': '*'
      typescript: '*'
  '@nrwl/cypress@*':
    dependencies:
      nx: '14'
      typescript: '*'
  '@nrwl/react@*':
    dependencies:
      eslint: '*'
      nx: '14'
      'tslib': '*'
  '@nrwl/storybook@*':
    dependencies:
      nx: '14'
      typescript: '*'
      webpack: '*'
  '@nrwl/web@*':
    dependencies:
      nx: '14'
      typescript: '*'
      '@types/node': '*'
  '@nrwl/eslint-plugin-nx@*':
    dependencies:
      eslint: '*'
      nx: '14'
