packageExtensions:
  "@commitlint/cli@*":
    dependencies:
      "@types/node": "*"
      ts-node: "*"
      typescript: "*"
  "@digitalroute/cz-conventional-changelog-for-jira@*":
    dependencies:
      "@types/node": "*"
      ts-node: "*"
      typescript: "*"
  "@nrwl/cypress@*":
    dependencies:
      nx: 14.5.10
      typescript: "*"
  "@nrwl/devkit@*":
    dependencies:
      nx: 14.5.10
      typescript: "*"
  "@nrwl/eslint-plugin-nx@*":
    dependencies:
      eslint: "*"
      nx: 14.5.10
  "@nrwl/jest@*":
    dependencies:
      nx: 14.5.10
      typescript: "*"
  "@nrwl/js@*":
    dependencies:
      nx: 14.5.10
  "@nrwl/linter@*":
    dependencies:
      typescript: "*"
  "@nrwl/react@*":
    dependencies:
      eslint: "*"
      nx: 14.5.10
      tslib: "*"
  "@nrwl/storybook@*":
    dependencies:
      nx: 14.5.10
      typescript: "*"
      webpack: "*"
  "@nrwl/web@*":
    dependencies:
      "@types/node": "*"
      nx: 14.5.10
      typescript: "*"
  "@ryansonshine/cz-conventional-changelog@*":
    dependencies:
      "@types/node": "*"
      ts-node: "*"
      typescript: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
